version: "3.5"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      common:
        aliases:
          - db

  ror:
    build: .
    volumes:
      - .:/airhost-hotels
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - common

networks:
  common: